### ISSUE TITLE
关于stablesr的一些问题

### ISSUE THREAD

**Issue by 947shibenben** [Arthurzhangsheng/CodeFormer_GUI#12]
怀着复杂的心情留个言。。。。。
几天前我做了一个comfyui工作流，原理是利用stablesr先对图片进行修复，然后再用tile+ipa+gemini进行放大，基本复刻了magnific ai的功能，然后我做成了教程发了B站。教程还挺受欢迎了，两天内有几十个人用各种方式留言，问我为什么manager搜不到stablesr，以及为啥安装我的教程git clone了comfyui stablesr后，所有和stablesr相关的节点都显示缺失都是红的。
然后经过一番研究，我才发现原来git上有两个comfyui_stablesr，我装的是你的版本，其他人装的是原作者的。
现在我只想陈恳请求大哥们有空加入一下comfyui的manager，这样插件才会被收录，然后能在comfyui里被搜到。毕竟使用者大部分都不会代码，基本得通过manager安装。

**Comment by Arthurzhangsheng** [comment]
我那个stableSR的库也是克隆朋友的库
