### ISSUE TITLE
是否可以增加mega云端档案连结?

### ISSUE THREAD

**Issue by s11005349** [Arthurzhangsheng/CodeFormer_GUI#2]
是否可以增加mega云端档案连结?
(国外使用者无法使用百度云盘)

**Comment by myjiejie** [comment]
https://mega.nz/file/3NUGHTzC#ICyE3yPSq1BMTvB-xg_iYR2lDXrA42jRouqkFaQIqek

**Comment by s11005349** [comment]
谢谢！
