### ISSUE TITLE
脸部修复效果不错，可是......

### ISSUE THREAD

**Issue by martjay** [Arthurzhangsheng/CodeFormer_GUI#3]
可是除了脸部其他地方的修复效果太差了，有没有其他方法能修复整图？

**Comment by Arthurzhangsheng** [comment]
你用第二个选项卡的全图清晰化，并且勾选上背景强化

**Comment by martjay** [comment]
> 你用第二个选项卡的全图清晰化，并且勾选上背景强化

已经用了那个选项了但是效果不好，到现在我也没找到比hiwpaw效果更好的修复工具，那个可以全图修复啊，他们到底用的是哪个技术？可惜现在hiwpaw在我的win11用不了，哎~
