### ISSUE TITLE
无法处理，提示如下：

### ISSUE THREAD

**Issue by star2k** [Arthurzhangsheng/CodeFormer_GUI#5]
开始处理...
Traceback (most recent call last):
  File "CodeFormer/inference_codeformer.py", line 96, in <module>
    success, image = vidcap.read()
cv2.error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\core\src\alloc.cpp:73: error: (-4:Insufficient memory) Failed to allocate 3072000 bytes in function 'cv::OutOfMemoryError'

**Comment by Arthurzhangsheng** [comment]
内存爆了，缩小视频时长，或者加大虚拟内存

**Comment by star2k** [comment]
> 内存爆了，缩小视频时长，或者加大虚拟内存

物理内存我有16G，虚拟内存所以我设置了1g，看物理内存，空余还有很多呀
