### ISSUE TITLE
AMD的GPU只能干瞪眼

### ISSUE THREAD

**Issue by WXpiero** [Arthurzhangsheng/CodeFormer_GUI#6]
全靠CPU，慢死了，是不是因为我是台式机系列的CPU的原因？不过好歹也是razen7啊。
另外老是会报内存不足错误，这个跑起来大概需要多少内存？我是16G

**Comment by Arthurzhangsheng** [comment]
运行需要英伟达显卡，而且对显存应该有一定要求，最低多少显存可运行我没测试过

**Comment by WXpiero** [comment]
好吧我把Riva128换上试试。。。。/(ㄒoㄒ)/~~
